### ISSUE TITLE
Any project description?

### ISSUE THREAD

**Issue by sxiii** [feelingsurf/docker-viewer#1]
Hi!

I was trying to make my own ubuntu-based docker container with feelingsurf when I found this.

At first; I wasn't able to launch it until I removed the downgrading to "fsviewer" user and added the --no-sandbox flag into FeelingSurfViewer binary. Then the container started normally.

But I would like to know if you @feelingsurf can share any information/documentation to the project. E.g. when I run the container (and it does some kind of health check; which is cool); it seems to be running; okay; but... How do I type-in my username & password to login into my account and earn? That would help a lot.

Thanks

**Comment by sxiii** [comment]
Actually, I found this in FAQ Section of FeelingSurf website:

### This topic covers an advanced usage of FeelingSurfViewer.
It is possible to run FeelingSurfViewer on a system without any graphical environment by using Docker.

* Install Docker on your system
* Pull the latest official feelingsurf/viewer image by running
`docker pull feelingsurf/viewer`
Spawn a new container
`docker run -d -e access_token=TOKEN feelingsurf/viewer`
Ensure everything is working by looking at your active surf sessions
Treat your access token as a password, keep it secret!

And I've also updated [documentation in my forked repo](github.com/sxiii/docker-viewer).

So closing the issue but I think @feelingsurf it would be better to include the documentation in github readme also. ;) Good luck guys!

**Comment by feelingsurf** [comment]
Thank you for your contribution @sxiii, we have added a project readme. Be aware you should not release your access token as it allows access to your FeelingSurf account. You should renew it asap from your user dashboard.

**Comment by sxiii** [comment]
Hi @feelingsurf - does it allow any other actions other then page views? Shouldn't it actually be limited to only getting views? Thanks.
